[package]
name = "rust-nix-starter"
version = "0.1.0"
authors = ["M. Ian Graham <games@miangraham.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
futures = "0.3"
log = "0.4"
