name: "Test"
on:
  push:
    branches:
      - stable
      - nightly
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Build
        run: nix build -vv
      - name: Run
        run: ./result/bin/rust-nix-starter
      - name: Shell Test
        run: nix-shell -vv --run "echo 'Shell works!'"
      - name: Print Rust Version Info
        run: |
          nix-shell --run "rustc --version"
          nix-shell --run "cargo --version"
